[package]
name = "diffo-watch"
description = "Live repository refresh service for Diffo"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
diffo-core.workspace = true
notify.workspace = true

[lints]
workspace = true
