[package]
name = "diffo-git"
description = "Git repository state collector for Diffo"
edition.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
diffo-core.workspace = true
nix.workspace = true
tempfile.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
