[package]
name = "diffo-explorer"
description = "Repository tree and file viewer tool for Diffo"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
crossterm.workspace = true
diffo-command.workspace = true
diffo-core.workspace = true
diffo-diff.workspace = true
diffo-highlight.workspace = true
diffo-ui.workspace = true
ratatui.workspace = true

[lints]
workspace = true
