[package]
name = "diffo-core"
description = "Repository state types and sources for Diffo"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
ron.workspace = true
serde.workspace = true

[lints]
workspace = true
