[package]
name = "diffo-core"
description = "Repository state types and sources for Diffo"
edition.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
ron.workspace = true
serde.workspace = true

[dev-dependencies]
insta = { workspace = true, features = ["ron"] }

[lints]
workspace = true
