[package]
name = "diffo-tui"
description = "Terminal UI for Diffo"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
crossterm.workspace = true
diffo-app.workspace = true
diffo-core.workspace = true
diffo-diff.workspace = true
diffo-highlight.workspace = true
ratatui.workspace = true

[lints]
workspace = true
