[package]
name = "diffo"
description = "A terminal UI for browsing Git state"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
crossterm.workspace = true
diffo-app.workspace = true
diffo-core.workspace = true
diffo-diff.workspace = true
diffo-explorer.workspace = true
diffo-git.workspace = true
diffo-tui.workspace = true
diffo-watch.workspace = true
diffo-workbench.workspace = true
ratatui.workspace = true
ron.workspace = true
serde.workspace = true
signal-hook.workspace = true

[lints]
workspace = true

[dev-dependencies]
diffo-app.workspace = true
diffo-core.workspace = true
diffo-e2e = { path = "../diffo-e2e" }
diffo-git.workspace = true
diffo-watch.workspace = true
ron.workspace = true
tempfile.workspace = true
