[package]
name = "diffo"
description = "A terminal UI for browsing Git state"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
diffo-core.workspace = true
diffo-git.workspace = true
diffo-tui.workspace = true
ratatui.workspace = true
ron.workspace = true

[lints]
workspace = true
