[package]
name = "diffo-e2e"
description = "End-to-end tests for Diffo"
edition.workspace = true
license.workspace = true
publish = false
readme = "README.md"
rust-version.workspace = true
version.workspace = true

[[test]]
name = "real_git_state"
path = "tests/real_git_state.rs"

[dependencies]
anyhow.workspace = true
portable-pty.workspace = true
tempfile.workspace = true
vt100.workspace = true

[dev-dependencies]
diffo-core.workspace = true
insta = { workspace = true, features = ["ron"] }
ron.workspace = true

[lints]
workspace = true
