[package]
name = "diffo-highlight"
description = "Bundled syntax highlighting for Diffo"
edition.workspace = true
license.workspace = true
readme = "README.md"
version.workspace = true

[dependencies]
diffo-diff.workspace = true
two-face.workspace = true

[dev-dependencies]
criterion.workspace = true
insta.workspace = true

[[bench]]
name = "highlight"
harness = false

[lints]
workspace = true
