[package]
name = "diffo-ui"
description = "Shared terminal UI primitives for Diffo tools"
edition.workspace = true
license.workspace = true
readme = "README.md"
version.workspace = true

[dependencies]
crossterm.workspace = true
diffo-core.workspace = true
diffo-highlight.workspace = true
ratatui.workspace = true
nucleo-matcher.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
